### ISSUE TITLE
ASM Hacks without source folder (only replSource)

### ISSUE THREAD

**Issue by axel7083** [haroohie-club/NitroPacker#11]
When I am trying to run `patch-arm9` to a with a `replSource` directory containing subdirectories with instructions to be directly replaced in the ARM9, it is failing with a `make: *** No targets specified and no makefile found.  Stop.`.

I would like to only use the feature replacing instructions to specific location in my arm9.bin file, is is possible or is there implementation contraints ?

**Comment by jonko0493** [comment]
Duplicate of #10.

Sorry for not getting around to this sooner; been having a bit of a stressful time as of late and am currently traveling. When I return, I'll be taking a look into this. :)

**Comment by jonko0493** [comment]
@axel7083 it's been like a year, but I did finally fix this! lol
