### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by chrisBioInf** [haroohie-club/NitroPacker#13]
Coming from a Linux system, the repository misses directions for compilation/installation.

No makefile is present, I assume .NET is needed as well as per the Readme, but what to do then?

**Comment by WiIIiam278** [comment]
Hey -- should be here: https://haroohie.club/chokuretsu/serial-loops/docs/introduction/installation#linux

**Comment by jonko0493** [comment]
@WiIIiam278 this is the NitroPacker repo, not SL. :)

That being said, @chrisBioInf, for Linux _installation_, it should be as simple as downloading and unpacking the tar.gz for Linux for the [latest release](https://github.com/haroohie-club/NitroPacker/releases/latest). That comes with a pre-compiled binary that shouldn't even require .NET for running.

You are correct that we should have instructions for building from source, though. That's also very simple though -- from a terminal within the cloned repository, you just type `dotnet build` after installing .NET and it will build a Linux executable. I'll assign this to myself to take on.

**Comment by WiIIiam278** [comment]
Oh lol whooops ;)

**Comment by chrisBioInf** [comment]
> @WiIIiam278 this is the NitroPacker repo, not SL. :)
> 
> That being said, @chrisBioInf, for Linux _installation_, it should be as simple as downloading and unpacking the tar.gz for Linux for the [latest release](https://github.com/haroohie-club/NitroPacker/releases/latest). That comes with a pre-compiled binary that shouldn't even require .NET for running.
> 
> You are correct that we should have instructions for building from source, though. That's also very simple though -- from a terminal within the cloned repository, you just type `dotnet build` after installing .NET and it will build a Linux executable. I'll assign this to myself to take on.

Ah, thanks, that makes sense. Yes, I meant build from source, not install (it was kinda late, where I live, oups).
Alright. 
`dotnet build` seems to do the trick after updating local .NET.

Thanks ~

**Comment by jonko0493** [comment]
Fixed in 982e7ee5c05901af7fd80b6f8ef80d5597dff5df
