### ISSUE TITLE
Fails with some DSi games

### ISSUE THREAD

**Issue by RibShark** [haroohie-club/NitroPacker#2]
Tested with Rayman (DSi), verified No-Intro file. Unpacked and then repacked immediately without changes, file is ~700kb smaller and no longer runs.

**Comment by jonko0493** [comment]
Interesting. Yeah, I can repro this -- my guess is that there's something we're doing wrong with DSiWare specifically. I'll look into this some more and see if I can figure it out.

**Comment by jonko0493** [comment]
Issue here is likely that we don't account for the DSi header at all when unpacking games. I'm currently working to add support for this to NitroPacker (sorry for the delay).

**Comment by jonko0493** [comment]
#15 introduces full unpacking for DSiWare games, but does not allow repacking. To be honest, I'm not exactly certain how possible repacking is. It's something I'll continue looking into, though.

**Comment by jonko0493** [comment]
I'm going to say this is as fixed as it's gonna get as of the v3.0 release in #15. I don't think it's possible to repack DSiWare games and have them work.
